# Enable/Disable maintenance mode.
global: false

# Enter the message you want to be shown when a player tries to join when maintenance mode is enabled.
kickMessage: "Maintenance mode enabled"

servers: []